### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by rain1024** [meotrics/meotrics#1]
Hôm nay mới biết đến meotrics. Mình thấy đây là một sản phẩm hấp dẫn.

Mình có góp ý nhỏ là nên thêm trang http://demo.meotrics.com/view/generalmetrics.php vào url của project để người xem tiện hơn.

**Comment by thanhpk** [comment]
Cảm ơn bạn, trang demo.meotrics.com hiện tại chỉ là trang tạm, bọn mình sẽ sớm thay bằng bản demo mới nhất
